[package]
name = "forecast-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
csv = "1.4.0"
dialoguer = "0.12.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
